#!/usr/bin/env python3
"""
통합 점검 파일 생성기

  python all/build.py          → all/check_all.sh, all/check_all.bat 다시 생성
  python all/build.py --check  → 생성 파일이 최신인지 확인 (다르면 종료 코드 1)

server/ · webwas/ · dbms/ 의 점검 스크립트를 수정한 뒤에는 반드시 다시 실행하세요.
생성 파일은 실행 시 임시 폴더에 원본 스크립트를 풀어 순서대로 실행합니다.
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HERE = os.path.join(ROOT, "all")

SH_FILES = [   # (저장소 경로, 풀어 놓을 이름)
    ("server/check_server.sh", "check_server.sh"),
    ("server/check_server_u.sh", "check_server_u.sh"),
    ("webwas/check_webwas.sh", "check_webwas.sh"),
    ("dbms/check_dbms.sh", "check_dbms.sh"),
    ("converter/eos_checker.py", "eos_checker.py"),
]
PS_FILES = [
    ("server/check_server.ps1", "check_server.ps1"),
    ("server/check_server_w.ps1", "check_server_w.ps1"),
    ("webwas/check_webwas.ps1", "check_webwas.ps1"),
    ("dbms/check_dbms_mssql.ps1", "check_dbms_mssql.ps1"),
    ("converter/eos_checker.py", "eos_checker.py"),
]
MARK = "#@@EMBED@@"

BAT_HEAD = r"""@echo off
setlocal
title Integrated Security Check
rem ================================================================
rem  check_all.bat - one file: auto-detects Web/WAS (IIS, Apache, Nginx,
rem  Tomcat, JEUS) and MSSQL, runs every matching check, zips the results.
rem  Generated by all/build.py - do not edit by hand.
rem ================================================================
net session >nul 2>&1
if %errorlevel% neq 0 (
    echo [ERROR] Run as Administrator.
    echo         Right-click this file ^> Run as administrator
    pause
    exit /b 1
)
echo ========================================
echo  Integrated Check - %COMPUTERNAME%
echo  Auto-detects Web/WAS and MSSQL
echo  1) EF  - Electronic Financial (SRV/WST/DBM)
echo  2) KISA - Critical Info Infra 2026 Guide (W/WEB/D)
echo  3) Both
echo ========================================
set "SEL="
set /p SEL=Select [1/2/3] (Enter=3):
set "VC_MODE=all"
if "%SEL%"=="1" set "VC_MODE=ef"
if "%SEL%"=="2" set "VC_MODE=mi"
set "VC_SELF=%~f0"
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "$s=[IO.File]::ReadAllText($env:VC_SELF,[Text.Encoding]::UTF8); $m='#__VC_PS'+'_START__'; iex $s.Substring($s.IndexOf($m))"
set "MSSQL_PASS="
pause
exit /b
#__VC_PS_START__
"""


def read(rel):
    with open(os.path.join(ROOT, rel), encoding="utf-8-sig") as f:
        text = f.read()
    return text if text.endswith("\n") else text + "\n"


def build_sh():
    parts = []
    for i, (rel, name) in enumerate(SH_FILES, 1):
        body = read(rel)
        delim = f"__VC_EOF_{i}__"
        assert f"\n{delim}\n" not in "\n" + body, f"{rel} 에 구분자 {delim} 가 있음"
        parts.append(f"# ── 내장: {rel} ──\ncat > \"$WORK/{name}\" <<'{delim}'\n{body}{delim}\n")
    runner = read("all/src/runner.sh")
    assert runner.count(MARK) == 1
    return runner.replace(MARK, "".join(parts).rstrip("\n"))


def build_bat():
    parts = []
    for rel, name in PS_FILES:
        body = read(rel)
        assert not any(l.startswith("'@") for l in body.splitlines()), f"{rel} 에 here-string 종료 기호('@)로 시작하는 줄이 있음"
        parts.append(f"# ── 내장: {rel} ──\nVC-Put '{name}' @'\n{body}'@\n")
    runner = read("all/src/runner.ps1")
    assert runner.count(MARK) == 1
    text = BAT_HEAD + runner.replace(MARK, "".join(parts).rstrip("\n"))
    return text.replace("\r\n", "\n").replace("\n", "\r\n")   # cmd.exe 는 CRLF 가 안전


def main():
    outputs = {
        os.path.join(HERE, "check_all.sh"): build_sh(),
        os.path.join(HERE, "check_all.bat"): build_bat(),
    }
    stale = []
    for path, text in outputs.items():
        data = text.encode("utf-8")   # .bat 은 BOM 없이 (BOM 이 있으면 첫 줄 @echo off 가 깨짐)
        if "--check" in sys.argv:
            try:
                with open(path, "rb") as f:
                    if f.read() != data:
                        stale.append(path)
            except FileNotFoundError:
                stale.append(path)
            continue
        with open(path, "wb") as f:
            f.write(data)
        if path.endswith(".sh"):
            os.chmod(path, 0o755)
        print(f"생성: {os.path.relpath(path, ROOT)}  ({text.count(chr(10)):,}줄)")
    if stale:
        print("최신 아님 (python all/build.py 로 다시 생성):", *[os.path.relpath(p, ROOT) for p in stale])
        sys.exit(1)


if __name__ == "__main__":
    main()
